wandb: Starting wandb agent 🕵️
2025-03-22 22:25:07,544 - wandb.wandb_agent - INFO - Running runs: []
2025-03-22 22:25:07,861 - wandb.wandb_agent - INFO - Agent received command: run
2025-03-22 22:25:07,861 - wandb.wandb_agent - INFO - Agent starting run with config:
	checkpoint.enabled: False
	datapipe.seed: 84
	schedule.phase1.iterations: 500
	schedule.phase1.lr_end: 0.1
	schedule.phase1.lr_start: 0.001
	schedule.phase2.iterations: 200
	schedule.phase2.lr_objective: 0.001
	schedule.phase3.iterations: 1000
	schedule.phase3.lr: 0.001
	schedule.phase3.rollout_steps_increments: 4
2025-03-22 22:25:07,864 - wandb.wandb_agent - INFO - About to run command: python -m torch.distributed.run --nnodes=1 --nproc_per_node=4 train_graphcast.py checkpoint.enabled=False datapipe.seed=84 schedule.phase1.iterations=500 schedule.phase1.lr_end=0.1 schedule.phase1.lr_start=0.001 schedule.phase2.iterations=200 schedule.phase2.lr_objective=0.001 schedule.phase3.iterations=1000 schedule.phase3.lr=0.001 schedule.phase3.rollout_steps_increments=4
2025-03-22 22:25:12,872 - wandb.wandb_agent - INFO - Running runs: ['wko54x6a']
[2025-03-22 22:25:41,715][main][INFO] - [94mRank: 1, Device: cuda:1[0m
[2025-03-22 22:25:41,715][main][INFO] - [94mRank: 3, Device: cuda:3[0m
[2025-03-22 22:25:41,715][main][INFO] - [94mRank: 2, Device: cuda:2[0m
[2025-03-22 22:25:41,722][main][INFO] - [94mRank: 0, Device: cuda:0[0m
wandb: WARNING Unable to verify login in offline mode.
wandb: WARNING Ignoring project 'DSM500_FPR' when running a sweep.
wandb: WARNING Ignoring entity 'schups' when running a sweep.
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/wandb/wandb/run-20250322_222542-wko54x6a
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run Baseline_64372_25/03/22_22:25:41_RUN_01
wandb: ⭐️ View project at https://wandb.ai/schups/DSM500_FPR
wandb: 🧹 View sweep at https://wandb.ai/schups/DSM500_FPR/sweeps/mpgn79e1
wandb: 🚀 View run at https://wandb.ai/schups/DSM500_FPR/runs/wko54x6a
[2025-03-22 22:25:43,868][trainer][INFO] - [94mSetting seed to 84[0m
[2025-03-22 22:25:43,947][cache][INFO] - [94mLoading cache for 'meshes'.[0m
[2025-03-22 22:25:43,947][cache][INFO] - [94mChecking if 'meshes' is cached.[0m
[2025-03-22 22:25:43,948][cache][INFO] - [94m-> HIT! '/iopsstor/scratch/cscs/stefschu/DSM500_FPR/cache/icosahedron_meshes.pickled' exists.[0m
[2025-03-22 22:25:43,949][cache][INFO] - [94m-> Checking guard 'MeshesCacheGuard'.[0m
[2025-03-22 22:25:48,394][trainer][INFO] - [94mModel created. Trainable parameters count is 35'248'149[0m
[2025-03-22 22:25:54,178][trainer][INFO] - [92mLoaded train datapipe of size 53'947 samples[0m
[2025-03-22 22:25:55,965][trainer][INFO] - [92mLoaded test datapipe of size 2'903 samples[0m
[2025-03-22 22:25:56,011][main][INFO] - [94mInitializing dataloaders...[0m
[2025-03-22 22:25:56,011][main][INFO] - [94mTraining started...[0m
[2025-03-22 22:26:52,045][trainer][INFO] - Iteration     1 | Train loss: 6.55 | Time taken:  8.51/47.52/56.03 sec | GPU memory: 79.1 GB | Global sample ID: 39278
[2025-03-22 22:26:52,506][trainer][INFO] - Iteration     2 | Train loss: 6.75 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 32914
[2025-03-22 22:26:52,905][trainer][INFO] - Iteration     3 | Train loss: 6.49 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 46909
[2025-03-22 22:26:53,763][trainer][INFO] - Iteration     4 | Train loss: 6.25 | Time taken:  0.19/ 0.29/ 0.48 sec | GPU memory: 82.1 GB | Global sample ID: 33024
[2025-03-22 22:26:54,159][trainer][INFO] - Iteration     5 | Train loss: 6.39 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 53769
[2025-03-22 22:26:54,547][trainer][INFO] - Iteration     6 | Train loss: 6.68 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 48692
[2025-03-22 22:26:54,950][trainer][INFO] - Iteration     7 | Train loss: 6.46 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 29769
[2025-03-22 22:26:55,498][trainer][INFO] - Iteration     8 | Train loss: 6.66 | Time taken:  0.00/ 0.43/ 0.43 sec | GPU memory: 82.1 GB | Global sample ID: 34724
[2025-03-22 22:26:55,883][trainer][INFO] - Iteration     9 | Train loss: 6.41 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 36387
[2025-03-22 22:26:56,294][trainer][INFO] - Iteration    10 | Train loss: 6.28 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 36237
[2025-03-22 22:26:56,686][trainer][INFO] - Iteration    11 | Train loss: 6.08 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 33738
[2025-03-22 22:26:57,080][trainer][INFO] - Iteration    12 | Train loss: 6.31 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 43183
[2025-03-22 22:26:57,486][trainer][INFO] - Iteration    13 | Train loss: 6.27 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 42939
[2025-03-22 22:26:57,890][trainer][INFO] - Iteration    14 | Train loss: 6.56 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 52723
[2025-03-22 22:26:58,286][trainer][INFO] - Iteration    15 | Train loss: 6.64 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 5903
[2025-03-22 22:26:58,777][trainer][INFO] - Iteration    16 | Train loss: 6.11 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 44261
[2025-03-22 22:26:59,284][trainer][INFO] - Iteration    17 | Train loss: 6.38 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 27422
[2025-03-22 22:26:59,747][trainer][INFO] - Iteration    18 | Train loss: 6.27 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 12162
[2025-03-22 22:27:00,129][trainer][INFO] - Iteration    19 | Train loss: 6.37 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 5842
[2025-03-22 22:27:00,523][trainer][INFO] - Iteration    20 | Train loss: 6.26 | Time taken:  0.00/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 19253
[2025-03-22 22:27:00,913][trainer][INFO] - Iteration    21 | Train loss: 6.14 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 19173
[2025-03-22 22:27:01,405][trainer][INFO] - Iteration    22 | Train loss: 5.75 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 41181
[2025-03-22 22:27:01,788][trainer][INFO] - Iteration    23 | Train loss: 6.19 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 39557
[2025-03-22 22:27:02,181][trainer][INFO] - Iteration    24 | Train loss: 5.89 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 35646
[2025-03-22 22:27:02,572][trainer][INFO] - Iteration    25 | Train loss: 5.88 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 51664
[2025-03-22 22:27:02,963][trainer][INFO] - Iteration    26 | Train loss: 5.88 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 19033
[2025-03-22 22:27:03,356][trainer][INFO] - Iteration    27 | Train loss: 5.35 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 53644
[2025-03-22 22:27:03,746][trainer][INFO] - Iteration    28 | Train loss: 5.35 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 44125
[2025-03-22 22:27:04,136][trainer][INFO] - Iteration    29 | Train loss: 5.45 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 11457
[2025-03-22 22:27:04,527][trainer][INFO] - Iteration    30 | Train loss: 5.60 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 7357
[2025-03-22 22:27:05,045][trainer][INFO] - Iteration    31 | Train loss: 5.53 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 29891
[2025-03-22 22:27:05,599][trainer][INFO] - Iteration    32 | Train loss: 5.40 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 9067
[2025-03-22 22:27:05,988][trainer][INFO] - Iteration    33 | Train loss: 5.08 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 40960
[2025-03-22 22:27:06,926][trainer][INFO] - Iteration    34 | Train loss: 5.08 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 47292
[2025-03-22 22:27:07,319][trainer][INFO] - Iteration    35 | Train loss: 4.95 | Time taken:  0.01/ 0.28/ 0.29 sec | GPU memory: 82.1 GB | Global sample ID: 16046
[2025-03-22 22:27:07,707][trainer][INFO] - Iteration    36 | Train loss: 4.91 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 28738
[2025-03-22 22:27:08,100][trainer][INFO] - Iteration    37 | Train loss: 5.07 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 50215
[2025-03-22 22:27:08,492][trainer][INFO] - Iteration    38 | Train loss: 4.82 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 30783
[2025-03-22 22:27:08,898][trainer][INFO] - Iteration    39 | Train loss: 4.68 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 47293
[2025-03-22 22:27:09,333][trainer][INFO] - Iteration    40 | Train loss: 4.72 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 27122
[2025-03-22 22:27:09,755][trainer][INFO] - Iteration    41 | Train loss: 4.62 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 42405
[2025-03-22 22:27:10,144][trainer][INFO] - Iteration    42 | Train loss: 4.34 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 35957
[2025-03-22 22:27:10,536][trainer][INFO] - Iteration    43 | Train loss: 4.22 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 53045
[2025-03-22 22:27:10,927][trainer][INFO] - Iteration    44 | Train loss: 4.06 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 45390
[2025-03-22 22:27:11,322][trainer][INFO] - Iteration    45 | Train loss: 4.01 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 41544
[2025-03-22 22:27:11,884][trainer][INFO] - Iteration    46 | Train loss: 4.07 | Time taken:  0.00/ 0.27/ 0.27 sec | GPU memory: 82.1 GB | Global sample ID: 3786
[2025-03-22 22:27:12,267][trainer][INFO] - Iteration    47 | Train loss: 3.74 | Time taken:  0.00/ 0.27/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 11605
[2025-03-22 22:27:12,661][trainer][INFO] - Iteration    48 | Train loss: 3.66 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 48647
[2025-03-22 22:27:13,238][trainer][INFO] - Iteration    49 | Train loss: 3.53 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 19586
[2025-03-22 22:27:13,623][trainer][INFO] - Iteration    50 | Train loss: 3.53 | Time taken:  0.00/ 0.28/ 0.28 sec | GPU memory: 82.1 GB | Global sample ID: 17615
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=500', 'schedule.phase1.lr_end=0.1', 'schedule.phase1.lr_start=0.001', 'schedule.phase2.iterations=200', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=1000', 'schedule.phase3.lr=0.001', 'schedule.phase3.rollout_steps_increments=4']
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=500', 'schedule.phase1.lr_end=0.1', 'schedule.phase1.lr_start=0.001', 'schedule.phase2.iterations=200', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=1000', 'schedule.phase3.lr=0.001', 'schedule.phase3.rollout_steps_increments=4']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 385, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1215, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error in MIXED operator `nvidia.dali.ops.MakeContiguous` encountered:

Can't allocate 1158676480 bytes on device 1.
Current pipeline object is no longer valid.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 385, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1215, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error in MIXED operator `nvidia.dali.ops.MakeContiguous` encountered:

Can't allocate 1158676480 bytes on device 0.
Current pipeline object is no longer valid.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['checkpoint.enabled=False', 'datapipe.seed=84', 'schedule.phase1.iterations=500', 'schedule.phase1.lr_end=0.1', 'schedule.phase1.lr_start=0.001', 'schedule.phase2.iterations=200', 'schedule.phase2.lr_objective=0.001', 'schedule.phase3.iterations=1000', 'schedule.phase3.lr=0.001', 'schedule.phase3.rollout_steps_increments=4']
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/train_graphcast.py", line 77, in main
    test_sample = next(iterator_testing)
  File "/iopsstor/scratch/cscs/stefschu/DSM500_FPR/modulus-baseline/modulus/datapipes/era5_hdf5.py", line 250, in __iter__
    _pipeline = dali_pth.DALIGenericIterator([self.pipe], [
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/plugin/base_iterator.py", line 385, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.10/dist-packages/nvidia/dali/pipeline.py", line 1215, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error in MIXED operator `nvidia.dali.ops.MakeContiguous` encountered:

Can't allocate 1158676480 bytes on device 3.
Current pipeline object is no longer valid.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: - 0.030 MB of 0.030 MB uploadedW0322 22:27:26.194000 189971 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 189975 closing signal SIGTERM
W0322 22:27:26.213000 189971 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 189977 closing signal SIGTERM
W0322 22:27:26.217000 189971 torch/distributed/elastic/multiprocessing/api.py:890] Sending process 189978 closing signal SIGTERM
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
E0322 22:27:27.154000 189971 torch/distributed/elastic/multiprocessing/api.py:862] failed (exitcode: 1) local_rank: 1 (pid: 189976) of binary: /iopsstor/scratch/cscs/stefschu/DSM500_FPR/env/venv_arm64/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_graphcast.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-22_22:27:26
  host      : nid007469
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 189976)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
2025-03-22 22:27:27,575 - wandb.wandb_agent - INFO - Cleaning up finished run: wko54x6a
wandb: Terminating and syncing runs. Press ctrl-c to kill.
